### ISSUE TITLE
Not running in EDT a note to others

### ISSUE THREAD

**Issue by Avec112** [DanielMichalski/spring-boot-swing-reservations#1]
I am working on a legacy system (Swing) and want to include Spring Boot. 

Looking around for examples I found this example among others. 
However Swing is supposed to run in the Event Dispatcher Thread (EDT) and this code does not. 
See https://docs.oracle.com/javase/tutorial/uiswing/concurrency/dispatch.html

Also to not lock up or block gui you are supposed to run SwingWorker threads (backround tasks).
https://docs.oracle.com/javase/tutorial/uiswing/concurrency/worker.html

To get the correct reference to MainMenuController this is sufficent.
```
// Ensure EDT
SwingUtilities.invokeLater(() -> { // Jdk8 Lambda
    MainMenuController mainMenuController = context.getBean(MainMenuController.class);
    mainMenuController.prepareAndOpenFrame();
});
```

**Comment by DanielMichalski** [comment]
Thanks. Fixed now.
