### ISSUE TITLE
Table "CLIENT" not found

### ISSUE THREAD

**Issue by bitsnaps** [DanielMichalski/spring-boot-swing-reservations#2]
Hi,
I got an error regard h2-ddl, saying Table "CLIENT" not found, it looks like h2 close connection after a period as mentioned [here](https://stackoverflow.com/questions/5763747/h2-in-memory-database-table-not-found
)
In order to fix that you need to keep your content you have to configure the url like this:
`url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`
Regards

**Comment by DanielMichalski** [comment]
It's fixed now.
