### ISSUE TITLE
Update record

### ISSUE THREAD

**Issue by robsonlira** [DanielMichalski/spring-boot-swing-reservations#3]
Hi Daniel!
Your material is very good, I just had a doubt but I still couldn't study your material, just based on the videos.
How does the user update? because it looks like it has only Inclusion and Exclusion

**Comment by DanielMichalski** [comment]
Hi,
Thanks. There's only a video that shows how to run the application.
Currently, there are only Adding and Removing functionalities without any edition. Perhaps I'll add in the near future.
Daniel

**Comment by robsonlira** [comment]
Obrigado!  
thanks!
